modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="cropcultivation"
version="${file.jarVersion}"
displayName="Crop Cultivation"
logoFile="banner.png"
authors="Elenterius"
description='''
A Mod that changes the growth mechanics of Crops.'''

[[dependencies.cropcultivation]]
modId="forge"
mandatory=true
versionRange="[31.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplefarming]]
modId="simplefarming"
mandatory=false
versionRange="[1.3.0,)"
ordering="AFTER"
side="BOTH"
