@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.creativechasm.cropcultivation.util;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;